apiVersion: v1
kind: ServiceAccount
metadata:
  name: r4c-cesium-viewer
  namespace: regions4climate
  labels:
    app.kubernetes.io/name: r4c-cesium-viewer
    app.kubernetes.io/instance: r4c-cesium-viewer
automountServiceAccountToken: true
